/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as InscricaoSucessoRouteImport } from './routes/inscricao.sucesso'
import { Route as InscricaoPendenteRouteImport } from './routes/inscricao.pendente'
import { Route as InscricaoFalhaRouteImport } from './routes/inscricao.falha'
import { Route as AdminTrabalhosRouteImport } from './routes/admin.trabalhos'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminInscritosRouteImport } from './routes/admin.inscritos'
import { Route as AdminExportarRouteImport } from './routes/admin.exportar'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminCuponsRouteImport } from './routes/admin.cupons'
import { Route as AdminCrachasRouteImport } from './routes/admin.crachas'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin.configuracoes'
import { Route as AdminCheckinJantarRouteImport } from './routes/admin.checkin-jantar'
import { Route as AdminCheckinRouteImport } from './routes/admin.checkin'
import { Route as AdminCertificadosRouteImport } from './routes/admin.certificados'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const InscricaoSucessoRoute = InscricaoSucessoRouteImport.update({
  id: '/inscricao/sucesso',
  path: '/inscricao/sucesso',
  getParentRoute: () => rootRouteImport,
} as any)
const InscricaoPendenteRoute = InscricaoPendenteRouteImport.update({
  id: '/inscricao/pendente',
  path: '/inscricao/pendente',
  getParentRoute: () => rootRouteImport,
} as any)
const InscricaoFalhaRoute = InscricaoFalhaRouteImport.update({
  id: '/inscricao/falha',
  path: '/inscricao/falha',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTrabalhosRoute = AdminTrabalhosRouteImport.update({
  id: '/admin/trabalhos',
  path: '/admin/trabalhos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInscritosRoute = AdminInscritosRouteImport.update({
  id: '/admin/inscritos',
  path: '/admin/inscritos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminExportarRoute = AdminExportarRouteImport.update({
  id: '/admin/exportar',
  path: '/admin/exportar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCuponsRoute = AdminCuponsRouteImport.update({
  id: '/admin/cupons',
  path: '/admin/cupons',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCrachasRoute = AdminCrachasRouteImport.update({
  id: '/admin/crachas',
  path: '/admin/crachas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/admin/configuracoes',
  path: '/admin/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCheckinJantarRoute = AdminCheckinJantarRouteImport.update({
  id: '/admin/checkin-jantar',
  path: '/admin/checkin-jantar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCheckinRoute = AdminCheckinRouteImport.update({
  id: '/admin/checkin',
  path: '/admin/checkin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCertificadosRoute = AdminCertificadosRouteImport.update({
  id: '/admin/certificados',
  path: '/admin/certificados',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/certificados': typeof AdminCertificadosRoute
  '/admin/checkin': typeof AdminCheckinRoute
  '/admin/checkin-jantar': typeof AdminCheckinJantarRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/crachas': typeof AdminCrachasRoute
  '/admin/cupons': typeof AdminCuponsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/exportar': typeof AdminExportarRoute
  '/admin/inscritos': typeof AdminInscritosRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/trabalhos': typeof AdminTrabalhosRoute
  '/inscricao/falha': typeof InscricaoFalhaRoute
  '/inscricao/pendente': typeof InscricaoPendenteRoute
  '/inscricao/sucesso': typeof InscricaoSucessoRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/certificados': typeof AdminCertificadosRoute
  '/admin/checkin': typeof AdminCheckinRoute
  '/admin/checkin-jantar': typeof AdminCheckinJantarRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/crachas': typeof AdminCrachasRoute
  '/admin/cupons': typeof AdminCuponsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/exportar': typeof AdminExportarRoute
  '/admin/inscritos': typeof AdminInscritosRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/trabalhos': typeof AdminTrabalhosRoute
  '/inscricao/falha': typeof InscricaoFalhaRoute
  '/inscricao/pendente': typeof InscricaoPendenteRoute
  '/inscricao/sucesso': typeof InscricaoSucessoRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/certificados': typeof AdminCertificadosRoute
  '/admin/checkin': typeof AdminCheckinRoute
  '/admin/checkin-jantar': typeof AdminCheckinJantarRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/crachas': typeof AdminCrachasRoute
  '/admin/cupons': typeof AdminCuponsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/exportar': typeof AdminExportarRoute
  '/admin/inscritos': typeof AdminInscritosRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/trabalhos': typeof AdminTrabalhosRoute
  '/inscricao/falha': typeof InscricaoFalhaRoute
  '/inscricao/pendente': typeof InscricaoPendenteRoute
  '/inscricao/sucesso': typeof InscricaoSucessoRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/certificados'
    | '/admin/checkin'
    | '/admin/checkin-jantar'
    | '/admin/configuracoes'
    | '/admin/crachas'
    | '/admin/cupons'
    | '/admin/dashboard'
    | '/admin/exportar'
    | '/admin/inscritos'
    | '/admin/login'
    | '/admin/trabalhos'
    | '/inscricao/falha'
    | '/inscricao/pendente'
    | '/inscricao/sucesso'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/certificados'
    | '/admin/checkin'
    | '/admin/checkin-jantar'
    | '/admin/configuracoes'
    | '/admin/crachas'
    | '/admin/cupons'
    | '/admin/dashboard'
    | '/admin/exportar'
    | '/admin/inscritos'
    | '/admin/login'
    | '/admin/trabalhos'
    | '/inscricao/falha'
    | '/inscricao/pendente'
    | '/inscricao/sucesso'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin/certificados'
    | '/admin/checkin'
    | '/admin/checkin-jantar'
    | '/admin/configuracoes'
    | '/admin/crachas'
    | '/admin/cupons'
    | '/admin/dashboard'
    | '/admin/exportar'
    | '/admin/inscritos'
    | '/admin/login'
    | '/admin/trabalhos'
    | '/inscricao/falha'
    | '/inscricao/pendente'
    | '/inscricao/sucesso'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminCertificadosRoute: typeof AdminCertificadosRoute
  AdminCheckinRoute: typeof AdminCheckinRoute
  AdminCheckinJantarRoute: typeof AdminCheckinJantarRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminCrachasRoute: typeof AdminCrachasRoute
  AdminCuponsRoute: typeof AdminCuponsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminExportarRoute: typeof AdminExportarRoute
  AdminInscritosRoute: typeof AdminInscritosRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminTrabalhosRoute: typeof AdminTrabalhosRoute
  InscricaoFalhaRoute: typeof InscricaoFalhaRoute
  InscricaoPendenteRoute: typeof InscricaoPendenteRoute
  InscricaoSucessoRoute: typeof InscricaoSucessoRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscricao/sucesso': {
      id: '/inscricao/sucesso'
      path: '/inscricao/sucesso'
      fullPath: '/inscricao/sucesso'
      preLoaderRoute: typeof InscricaoSucessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscricao/pendente': {
      id: '/inscricao/pendente'
      path: '/inscricao/pendente'
      fullPath: '/inscricao/pendente'
      preLoaderRoute: typeof InscricaoPendenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscricao/falha': {
      id: '/inscricao/falha'
      path: '/inscricao/falha'
      fullPath: '/inscricao/falha'
      preLoaderRoute: typeof InscricaoFalhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/trabalhos': {
      id: '/admin/trabalhos'
      path: '/admin/trabalhos'
      fullPath: '/admin/trabalhos'
      preLoaderRoute: typeof AdminTrabalhosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/inscritos': {
      id: '/admin/inscritos'
      path: '/admin/inscritos'
      fullPath: '/admin/inscritos'
      preLoaderRoute: typeof AdminInscritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/exportar': {
      id: '/admin/exportar'
      path: '/admin/exportar'
      fullPath: '/admin/exportar'
      preLoaderRoute: typeof AdminExportarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cupons': {
      id: '/admin/cupons'
      path: '/admin/cupons'
      fullPath: '/admin/cupons'
      preLoaderRoute: typeof AdminCuponsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/crachas': {
      id: '/admin/crachas'
      path: '/admin/crachas'
      fullPath: '/admin/crachas'
      preLoaderRoute: typeof AdminCrachasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/admin/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/checkin-jantar': {
      id: '/admin/checkin-jantar'
      path: '/admin/checkin-jantar'
      fullPath: '/admin/checkin-jantar'
      preLoaderRoute: typeof AdminCheckinJantarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/checkin': {
      id: '/admin/checkin'
      path: '/admin/checkin'
      fullPath: '/admin/checkin'
      preLoaderRoute: typeof AdminCheckinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/certificados': {
      id: '/admin/certificados'
      path: '/admin/certificados'
      fullPath: '/admin/certificados'
      preLoaderRoute: typeof AdminCertificadosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminCertificadosRoute: AdminCertificadosRoute,
  AdminCheckinRoute: AdminCheckinRoute,
  AdminCheckinJantarRoute: AdminCheckinJantarRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminCrachasRoute: AdminCrachasRoute,
  AdminCuponsRoute: AdminCuponsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminExportarRoute: AdminExportarRoute,
  AdminInscritosRoute: AdminInscritosRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminTrabalhosRoute: AdminTrabalhosRoute,
  InscricaoFalhaRoute: InscricaoFalhaRoute,
  InscricaoPendenteRoute: InscricaoPendenteRoute,
  InscricaoSucessoRoute: InscricaoSucessoRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
