/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminTrabalhosRouteImport } from './routes/admin.trabalhos'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminInscritosRouteImport } from './routes/admin.inscritos'
import { Route as AdminExportarRouteImport } from './routes/admin.exportar'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminCuponsRouteImport } from './routes/admin.cupons'
import { Route as AdminCrachasRouteImport } from './routes/admin.crachas'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin.configuracoes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTrabalhosRoute = AdminTrabalhosRouteImport.update({
  id: '/admin/trabalhos',
  path: '/admin/trabalhos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInscritosRoute = AdminInscritosRouteImport.update({
  id: '/admin/inscritos',
  path: '/admin/inscritos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminExportarRoute = AdminExportarRouteImport.update({
  id: '/admin/exportar',
  path: '/admin/exportar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCuponsRoute = AdminCuponsRouteImport.update({
  id: '/admin/cupons',
  path: '/admin/cupons',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCrachasRoute = AdminCrachasRouteImport.update({
  id: '/admin/crachas',
  path: '/admin/crachas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/admin/configuracoes',
  path: '/admin/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/crachas': typeof AdminCrachasRoute
  '/admin/cupons': typeof AdminCuponsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/exportar': typeof AdminExportarRoute
  '/admin/inscritos': typeof AdminInscritosRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/trabalhos': typeof AdminTrabalhosRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/crachas': typeof AdminCrachasRoute
  '/admin/cupons': typeof AdminCuponsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/exportar': typeof AdminExportarRoute
  '/admin/inscritos': typeof AdminInscritosRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/trabalhos': typeof AdminTrabalhosRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/crachas': typeof AdminCrachasRoute
  '/admin/cupons': typeof AdminCuponsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/exportar': typeof AdminExportarRoute
  '/admin/inscritos': typeof AdminInscritosRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/trabalhos': typeof AdminTrabalhosRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/configuracoes'
    | '/admin/crachas'
    | '/admin/cupons'
    | '/admin/dashboard'
    | '/admin/exportar'
    | '/admin/inscritos'
    | '/admin/login'
    | '/admin/trabalhos'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/configuracoes'
    | '/admin/crachas'
    | '/admin/cupons'
    | '/admin/dashboard'
    | '/admin/exportar'
    | '/admin/inscritos'
    | '/admin/login'
    | '/admin/trabalhos'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin/configuracoes'
    | '/admin/crachas'
    | '/admin/cupons'
    | '/admin/dashboard'
    | '/admin/exportar'
    | '/admin/inscritos'
    | '/admin/login'
    | '/admin/trabalhos'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminCrachasRoute: typeof AdminCrachasRoute
  AdminCuponsRoute: typeof AdminCuponsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminExportarRoute: typeof AdminExportarRoute
  AdminInscritosRoute: typeof AdminInscritosRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminTrabalhosRoute: typeof AdminTrabalhosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/trabalhos': {
      id: '/admin/trabalhos'
      path: '/admin/trabalhos'
      fullPath: '/admin/trabalhos'
      preLoaderRoute: typeof AdminTrabalhosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/inscritos': {
      id: '/admin/inscritos'
      path: '/admin/inscritos'
      fullPath: '/admin/inscritos'
      preLoaderRoute: typeof AdminInscritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/exportar': {
      id: '/admin/exportar'
      path: '/admin/exportar'
      fullPath: '/admin/exportar'
      preLoaderRoute: typeof AdminExportarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cupons': {
      id: '/admin/cupons'
      path: '/admin/cupons'
      fullPath: '/admin/cupons'
      preLoaderRoute: typeof AdminCuponsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/crachas': {
      id: '/admin/crachas'
      path: '/admin/crachas'
      fullPath: '/admin/crachas'
      preLoaderRoute: typeof AdminCrachasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/admin/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminCrachasRoute: AdminCrachasRoute,
  AdminCuponsRoute: AdminCuponsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminExportarRoute: AdminExportarRoute,
  AdminInscritosRoute: AdminInscritosRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminTrabalhosRoute: AdminTrabalhosRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
